name: PHP Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:  ubuntu-latest

    steps:
      - name: Deploy to Ec2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }} 
          username: ubuntu 
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /var/www/html
            git pull origin main
            pm2 delete phppro || true
            pm2 start "php -S 0.0.0.0:8088 -t ." --name phppro
            pm2 save
